/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiDetail: typeof import('./src/components/ApiDetail.vue')['default']
    ApiItem: typeof import('./src/components/ApiItem.vue')['default']
    ApiList: typeof import('./src/components/ApiList.vue')['default']
    CollapseItem: typeof import('./src/components/CollapseItem.vue')['default']
    CopyIcon: typeof import('./src/components/CopyIcon.vue')['default']
    HighlightCode: typeof import('./src/components/HighlightCode.vue')['default']
    Method: typeof import('./src/components/Method.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsCard: typeof import('./src/components/TabsCard.vue')['default']
    UrlInput: typeof import('./src/components/UrlInput.vue')['default']
  }
}
